# Generated by Django 5.0.3 on 2024-04-17 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=62)),
                ('title', models.CharField(max_length=144)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='articles.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=62)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('is_en', models.BooleanField(default=True)),
                ('og_description', models.TextField(max_length=164)),
                ('image', models.ImageField(null=True, upload_to='post_images/')),
                ('tags', models.ManyToManyField(to='articles.tag')),
            ],
        ),
    ]
