# Generated by Django 5.1.3 on 2024-11-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_en',
        ),
        migrations.AddField(
            model_name='post',
            name='locale',
            field=models.CharField(choices=[('Farsi', 'FARSI'), ('English', 'ENGLISH'), ('Italian', 'ITALIAN')], default='FARSI', max_length=20),
        ),
    ]
