# Generated by Django 5.1 on 2024-11-07 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SponsorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("contact_name", models.CharField(max_length=100)),
                (
                    "company_website",
                    models.TextField(
                        validators=[django.core.validators.URLValidator()]
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "sponsorship_type",
                    models.CharField(
                        choices=[
                            ("financial", "Financial"),
                            ("equipment", "Equipment"),
                            ("services", "Services"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Describe your sponsorship offer or any questions."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TeammateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone_number", models.CharField(max_length=13)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("team_leader", "Team Leader"),
                            ("project_manager", "Project Manager"),
                            (
                                "finance_sponsorship_manager",
                                "Finance & Sponsorship Manager",
                            ),
                            ("powertrain_engineer", "Powertrain Engineer"),
                            ("fuel_system_engineer", "Fuel System Engineer"),
                            ("cooling_system_engineer", "Cooling System Engineer"),
                            (
                                "battery_management_system_engineer",
                                "Battery Management System (BMS) Engineer",
                            ),
                            ("chassis_engineer", "Chassis Engineer"),
                            (
                                "bodywork_aerodynamics_engineer",
                                "Bodywork & Aerodynamics Engineer",
                            ),
                            ("suspension_engineer", "Suspension Engineer"),
                            ("steering_brakes_engineer", "Steering & Brakes Engineer"),
                            ("electronics_engineer", "Electronics Engineer"),
                            ("control_systems_engineer", "Control Systems Engineer"),
                            (
                                "software_telemetry_engineer",
                                "Software & Telemetry Engineer",
                            ),
                            ("transmission_engineer", "Transmission Engineer"),
                            ("driveline_engineer", "Driveline Engineer"),
                            ("vehicle_dynamics_engineer", "Vehicle Dynamics Engineer"),
                            (
                                "simulation_testing_engineer",
                                "Simulation & Testing Engineer",
                            ),
                            ("manufacturing_engineer", "Manufacturing Engineer"),
                            ("materials_engineer", "Materials Engineer"),
                            ("testing_engineer", "Testing Engineer"),
                            ("data_analysis_engineer", "Data Analysis Engineer"),
                            ("business_plan_manager", "Business Plan Manager"),
                            ("marketing_media_manager", "Marketing & Media Relations"),
                            ("event_coordinator", "Event Coordinator"),
                            ("driver", "Driver"),
                            ("pit_crew", "Pit Crew"),
                            ("safety_officer", "Safety Officer"),
                            ("compliance_engineer", "Compliance Engineer"),
                            (
                                "autonomous_systems_engineer",
                                "Autonomous Systems Engineer",
                            ),
                            ("computer_vision_engineer", "Computer Vision Engineer"),
                            (
                                "lidar_sensor_integration_engineer",
                                "LIDAR & Sensor Integration Engineer",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("resume", models.FileField(upload_to="resumes/")),
                (
                    "linkedin",
                    models.TextField(
                        validators=[django.core.validators.URLValidator()]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_education_academy_name", models.CharField(max_length=200)),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("undergraduate", "Undergraduate"),
                            ("postgraduate", "Postgraduate"),
                            ("phd", "PhD"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "wants_further_study",
                    models.BooleanField(choices=[(True, "Yes"), (False, "No")]),
                ),
            ],
        ),
    ]
