# Generated by Django 5.1.3 on 2024-11-17 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_receive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammaterequest',
            name='website',
            field=models.TextField(default='none', validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
